# Generated by Django 3.2.5 on 2021-07-05 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('short_description', models.TextField(max_length=60)),
                ('description', models.TextField()),
                ('outcome', models.CharField(max_length=400)),
                ('prerequisite', models.CharField(max_length=400)),
                ('language', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('num_of_rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
