# Generated by Django 3.2.5 on 2021-07-06 07:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_registeredcourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredCourses',
            new_name='RegisteredCourse',
        ),
    ]
